In [1]:
pip install yelpapi

Requirement already satisfied: yelpapi in /Users/marinaduarte/opt/anaconda3/lib/python3.8/site-packages (2.4.0)
Requirement already satisfied: requests in /Users/marinaduarte/opt/anaconda3/lib/python3.8/site-packages (from yelpapi) (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/marinaduarte/opt/anaconda3/lib/python3.8/site-packages (from requests->yelpapi) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /Users/marinaduarte/opt/anaconda3/lib/python3.8/site-packages (from requests->yelpapi) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/marinaduarte/opt/anaconda3/lib/python3.8/site-packages (from requests->yelpapi) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/marinaduarte/opt/anaconda3/lib/python3.8/site-packages (from requests->yelpapi) (2020.6.20)
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/marinaduarte/opt/anaconda3/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [13]:
# Get list of 100 largest cities in US by population

from yelpapi import YelpAPI
import pandas as pd
import requests
url = "https://www.nationalpopularvote.com/100-biggest-cities-have-59849899-people-and-rural-areas-have-59492267-people"
response = requests.get(url)
tables = pd.read_html(url)
cities = tables[0]
cities = cities.rename(columns=cities.iloc[0])
cities = cities[['City']]
city_list = (cities['City']).tolist()
city_list = city_list[1:16]
len(city_list)

15

In [14]:
client_id = 'QFEVJMDVtV4QHEUVepKk1w'
api_key = '9OcFOk6yy50Q515gwbQBpIJkBjiSbLfJkERDt0PBL2ccytMe8euGxRQsECS6DbH0P1vvBjxMHaVvnhVY-BDXpHLCzugOE5l6gcNjMBGArfR6d4MpjclMXHnjVaIHYHYx'



yelp_api = YelpAPI(api_key)

In [22]:
records = []

term = 'restaurant'
search_limit = 50

for location in city_list:
    response = yelp_api.search_query(term = term,
                                  location = location,
                                  limit = search_limit)

    for business in response['businesses']:
        #print(business.keys())
        try:
            record = {
                'id':business['id'],
                'review_count':business['review_count'],
                'location': business['location']['city'],
                'category': business['categories'][0]['title'],
                'rating': business['rating'],
                'price':business['price'],
                'latitude':business['coordinates']['latitude'],
                'longitude':business['coordinates']['longitude']
            }
        except:
            print('Record not found')
            pass
    
        records.append(record)
        
        
#print(records)

Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found
Record not found

In [23]:
city_list

['New York, NY',
 'Los Angeles, CA',
 'Chicago, IL',
 'Houston, TX',
 'Philadelphia, PA',
 'Phoenix, AZ',
 'San Antonio, TX',
 'San Diego, CA',
 'Dallas, TX',
 'San Jose, CA',
 'Jacksonville, FL',
 'Indianapolis, IN',
 'San Francisco, CA',
 'Austin, TX',
 'Columbus, OH']

In [24]:
df = pd.DataFrame.from_dict(records)
df

,id,review_count,location,category,rating,price,latitude,longitude
0,ETgJqJHV7BW6pIr9Ox74sA,2699,New York,French,4.5,$$,40.732700,-73.997660
1,xt4sa64WOrpJvZBDPNPNYg,4298,New York,Comfort Food,4.0,$$,40.786650,-73.975528
2,q11TljTQd33XCWlVoPyRqg,228,Brooklyn,American (New),4.0,$$,40.702241,-73.995539
3,B3_K2kUVbYOU0VaLcj_LTw,3522,New York,Thai,4.5,$$,40.739020,-73.990650
4,Ms3CAGddVbgetiQrpzqxPQ,1411,Brooklyn,Barbeque,4.0,$$,40.674860,-74.016020
...,...,...,...,...,...,...,...,...
745,ENDUhy6ZIw2jdHwlBZGAdg,351,Columbus,Breakfast & Brunch,4.0,$$,39.995120,-83.014180
746,ENDUhy6ZIw2jdHwlBZGAdg,351,Columbus,Breakfast & Brunch,4.0,$$,39.995120,-83.014180
747,7fHPqJu0RGpE7GjAqh4Csg,127,Columbus,Polish,4.5,$,39.965539,-82.991840
748,7fHPqJu0RGpE7GjAqh4Csg,127,Columbus,Polish,4.5,$,39.965539,-82.991840
749,7fHPqJu0RGpE7GjAqh4Csg,127,Columbus,Polish,4.5,$,39.965539,-82.991840